CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

--;;

CREATE EXTENSION IF NOT EXISTS citext;

--;;

SET TIME ZONE 'UTC';

--;;

CREATE TABLE IF NOT EXISTS settings (
key varchar(254) UNIQUE NOT NULL PRIMARY KEY,
value TEXT NOT NULL);

--;;

CREATE TABLE IF NOT EXISTS workspace (
id UUID DEFAULT uuid_generate_v4() UNIQUE NOT NULL PRIMARY KEY,
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
created_by UUID NOT NULL,
name citext UNIQUE NOT NULL,
archived BOOLEAN DEFAULT false);